# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency

url    : "https://betterplumbing.co.nz" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog

title      : Better Plumbing
email      : calvin@betterplumbing.co.nz #this is also the email contact forms will go to
description: "Welcome to Better Plumbing - Your Trusted Plumbing Experts. Our team of highly skilled and experienced plumbers provides comprehensive solutions for all your plumbing needs. From residential to commercial projects, we handle any plumbing challenge with precision and efficiency. Our licensed plumbers stay up-to-date with the latest plumbing technology and techniques, ensuring superior results. We prioritize promptness, reliability, and customer satisfaction. Whether you need routine repairs, installations, or a complete plumbing system overhaul, our comprehensive services have you covered. Contact Better Plumbing today for reliable, efficient, and top-quality plumbing solutions. Experience the difference of working with true professionals."
author     : Better Plumbing
logo:     #optional, defaults to site title
 path: assets\img\logo.jpg
 height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/xzblpalg"
formspree_recaptcha_key: "6LeFhNwmAAAAAJRvUa32Axk3SSBvd3rUIZzz9Rda"